### ISSUE TITLE
Notification Pop-Up Background Unthemed (Transparent)

### ISSUE THREAD

**Issue by 5OBHAN** [sanoojes/Spicetify-Lucid#90]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.53.440.g7b2f582a
- Installed from: Spotify site
- Spicetify version: v2.38.7
- Color scheme: Dark
- Extensions: adblock.js, playOnYouTube.js, romaja_lyrics.js, romaji_lyrics.js, full-queue-clear.js, seekonscroll.js, keyboardShortcut.js, shuffle+.js, scannables.js, volumePercentage.js, playback-bar-waveform.js, beautiful-lyrics.mjs, theme.js
- Custom apps: marketplace
- Lucid installation method: Spicetify Marketplace
- Font: JetBrains Mono
```

### Description

1. Play a playlist where some songs are unavailable.
2. When the playlist goes to these unavailable songs to play
3. It displays a **Notification Pop-Up** saying _`Spotify can't play this right now. If you have the file on your computer you can import it.`_
4. Skips to the next available song.

> **Note:** The popup notification also displays when we **Add to Liked Songs** / **Add to Playlist**

The background should match the **Background Option** we choose in **Lucid Settings** (`Animated / Static / Solid`)

### Screenshots

![Screenshot 2025-01-14 205429](https://github.com/user-attachments/assets/16388780-ed24-4c0f-8975-2c8025d6f6df)

**Comment by 5OBHAN** [comment]
### Meanwhile, I've created a workaround with **CSS Snippet**

![Screenshot 2025-01-14 205557](https://github.com/user-attachments/assets/6464695b-76b9-4d4f-8b6a-3d0aea90e56c)

Just add this under snippets tab...

_For those with_ **Background Option**: `Animated` / `Static`
```css
.notistack-Snackbar .BoxComponent-box-elevated {
    background-color: var(--background-color, rgba(var(--spice-rgb-player, var(--spice-rgb-card)), 0.5));
    border: var(--border-thickness) var(--border-style, solid) var(--border-color, rgba(var(--spice-rgb-text), 0.125));
    border-radius: var(--border-radius, 0.5rem);
    -webkit-backdrop-filter: opacity(var(--backdrop-opacity, 1)) blur(var(--backdrop-blur, 1rem)) saturate(var(--saturation, 1.1)) brightness(var(--brightness, 1)) contrast(var(--contrast, 1.2));
    backdrop-filter: opacity(var(--backdrop-opacity, 1)) blur(var(--backdrop-blur, 1rem)) saturate(var(--saturation, 1.1)) brightness(var(--brightness, 1)) contrast(var(--contrast, 1.2));
}
```

_For those with_ **Background Option**: `Solid`
```css
.notistack-Snackbar .BoxComponent-box-elevated {
    background-color: var(--background-color, rgba(var(--spice-rgb-player, var(--spice-rgb-card)), 1));
    border: var(--border-thickness) var(--border-style, solid) var(--border-color, rgba(var(--spice-rgb-text), 0.125));
    border-radius: var(--border-radius, 0.5rem);
    -webkit-backdrop-filter: opacity(var(--backdrop-opacity, 1)) saturate(var(--saturation, 1.1)) brightness(var(--brightness, 1)) contrast(var(--contrast, 1.2));
    backdrop-filter: opacity(var(--backdrop-opacity, 1)) saturate(var(--saturation, 1.1)) brightness(var(--brightness, 1)) contrast(var(--contrast, 1.2));
}
```

> **Note:** It does not change with Background Options you choose. So, use either one of snippet
